name: Check Generated

on:
    push:
        paths:
            - 'logic/**/main/**/*Assertions.kt'
            - 'misc/tools/readme-examples/**/*'
            - 'README.md'
    pull_request:
        paths:
            - 'logic/**/main/**/*Assertions.kt'
            - 'misc/tools/readme-examples/**/*'
            - 'README.md'

jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: true
            matrix:
                java_version: [11]
        steps:
            -   uses: actions/checkout@v2
            -   name: "Set up JDK ${{ matrix.java_version }}"
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java_version }}

            -   name: check generated files committed
                run: ./gradle/scripts/check-generated-committed.sh
                shell: bash
