name: Windows

on: [push, pull_request]

jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: true
            matrix:
                java_version: [9, 10, 11, 12, 13, 14]

        steps:
            -   uses: actions/checkout@v1
            -   name: "Set up JDK ${{ matrix.java_version }}"
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java_version }}
            -   name: buildNonDeprecatedJvm
                run: ./gradlew buildNonDeprecatedJvm
                env:
                  CI: true
                  ATRIUM_ANDROID_JAR: ./android.jar
            -   name: Upload windows build code coverage
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    flags: current_windows
                    # too many timeout errors, let's not fail at the moment
                    #fail_ci_if_error: true

            -   name: build jasmine sample
                run: samples\js\jasmine\gradlew -p samples\js\jasmine build

            -   name: build mocha sample
                run: samples\js\mocha\gradlew -p samples\js\mocha build

            -   name: build Spek sample
                run: samples\jvm\spek\gradlew -p samples\jvm\spek build

            -   name: build Junit5 sample
                run: samples\jvm\junit5\gradlew -p samples\jvm\junit5 build

            -   name: build MPP sample
                run: samples\multiplatform\gradlew -p samples\multiplatform build

            -   name: composite build atrium-samples
                run: misc\tools\atrium-samples-test\gradlew -p misc\tools\atrium-samples-test build

            -   name: check dexer
                run: |
                    wget "https://github.com/Sable/android-platforms/blob/master/android-28/android.jar?raw=true" -P "./android.jar"
                    ./gradlew checkDexer
                shell: bash
                env:
                    CI: true
                    ATRIUM_ANDROID_JAR: ./android.jar

